name: 报告bug/Bug report 
description: Let us know about a bug that occurs without other mods
title: ''
labels: bug
assignees: []
body:
- type: dropdown
  attributes:
    label: 模组加载器/Mod Loader
    description: What mod loader does this issue occur on?
    options:
      - Forge
      - Fabric
  validations:
    required: true
- type: textarea
  attributes:
    label: 描述问题现象/Issue description
    description: Describe what happens, and what you expect to happen instead
  validations:
    required: true
- type: textarea
  attributes:
    label: 描述问题复现步骤/Issue reproduction
    description: Describe how to reproduce your issue
  validations:
    required: true
- type: textarea
  attributes:
    label: 日志文件/Logs
    description: Go to `.minecraft/logs` and drag and drop the `latest.log` and `debug.log` file into this text field
