name: 建议/suggest
description: Let us know about a bug that occurs without other mods
title: '[suggest]'
labels: suggest
assignees: []
body:
- type: textarea
  attributes:
    label: 有何想法?/Any thoughts?
  validations:
    required: false
